### PR TITLE
Update Language and Terminology sections with TermWeb

### PR DESCRIPTION
**Pull request by dariavladykina**
Updated Language (#286) and Terminology sections with information about TermWeb.

### CODE REVIEW

**Comment by Amrita42** [comment]
Commented >> https://github.com/SUSE/doc-styleguide/issues/286#issuecomment-2095179572

**Comment by jfaltenbacher** [comment]
I believe it is sufficient to mention that visiting this link requires a SUSE account (which is available to all employees by default and can be requested for externals at https://www.suse.com/account/create/)

**Comment by dariavladykina** [comment]
It is already mentioned in the Terminology section. I don't believe we need to dwell on it more than once.

**Comment by Amrita42** [comment]
ok thanks

**Review by Amrita42 — APPROVED** [review]

**Review by jfaltenbacher — APPROVED** [review]
LGTM

**Pull request merged**
